# Generated by Django 5.1.11 on 2025-08-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_or_phone",
            field=models.CharField(
                default="sudeep.b@stackpro.in", max_length=100, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.FileField(
                blank=True,
                default="user_images/default.png",
                null=True,
                upload_to="user_images/",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
