# Generated by Django 5.1.11 on 2025-08-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_email_or_phone_user_image_user_location_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
