# Generated by Django 5.2.5 on 2025-08-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="active",
        ),
    ]
