# Generated by Django 5.2.5 on 2025-08-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_cart_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(default="unknown"),
            preserve_default=False,
        ),
    ]
